import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, mkdir, writeFile, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { deflateSync } from 'node:zlib';
import { scanEntry, auditPackage, inspectableText } from './check-release-hygiene.mjs';
import { createZip, collectFiles } from './build-packages.mjs';

const entry = (text, name = 'product/includes/example.php') => ({ name, content: Buffer.from(text) });
for (const name of ['AGENTS.md', 'tests/check.php', '.GITHUB/workflows/check.yml', '.cache/result.json',
    'playwright/.auth/session.json', 'task-release.md', 'handoff.md', 'qa-report.md', 'docs/content-index-regression.md',
    'playwright.config.js', 'helper.spec.js', '.env.production', 'credentials.json', 'cookies.json', 'id_ed25519', '.ssh/config', 'mi-runtime-regression-probes/probe.php']) {
    test('rejects development filename: ' + name, () => {
        assert.ok(scanEntry(entry('', 'product/' + name)).some(item => item.rule === 'development-file'));
    });
}
const cases = [
    ['Windows backslashes', 'C:\\Users\\Example\\project', 'workstation-path'],
    ['Windows forward slashes', 'E:/Personal/project', 'workstation-path'],
    ['Unix home', '/home/example/project', 'workstation-path'],
    ['macOS home', '/Users/example/project', 'workstation-path'],
    ['auth path', 'playwright/.auth/session.json', 'internal-path'],
    ['diagnostic code', 'function rest_bootstrap_probe() {}', 'internal-process'],
    ['private key', '-----BEGIN OPENSSH PRIVATE KEY-----', 'private-key'],
    ['password literal', "password = 'fixture-only-value'", 'credential-literal'],
    ['JSON API key', '{"api_key": "fixture-only-value"}', 'credential-literal'],
    ['long generic token', "const token = 'fixture-only-value-long-enough';", 'long-secret-literal'],
    ['PHP secret constant', "define('AUTH_KEY', 'fixture-only-value');", 'wordpress-secret'],
    ['provider token', 'ghp_' + 'x'.repeat(36), 'provider-token'],
    ['authorization header', 'Bearer ' + 'x'.repeat(25), 'authorization-token'],
    ['URL credentials', 'https://example:fixture-only-value@example.invalid/', 'authorization-token'],
    ['saved browser state', '{"cookies": [], "origins": []}', 'authentication-state'],
];
for (const [label, text, rule] of cases) {
    test('rejects ' + label, () => {
        const findings = scanEntry(entry(text));
        assert.ok(findings.some(item => item.rule === rule), JSON.stringify(findings));
        assert.ok(findings.every(item => item.file === 'product/includes/example.php'));
    });
}
for (const term of ['Codex', 'OpenAI', 'ChatGPT', 'LLM', 'LLMs', 'large language model', 'ai-generated', 'generated by']) {
    test('rejects packaged tooling term: ' + term, () => {
        assert.ok(scanEntry(entry('Comment: ' + term)).some(item => item.rule === 'tooling-reference'));
    });
}
test('uses word boundaries and permits normal runtime/security language', () => {
    assert.deepEqual(scanEntry(entry('codexterity codecs openair chillmusic assistant agent prompt post_password_required() '
        + 'credentials: "same-origin"; /wp/v2/users/1 https://example.invalid/home/page')), []);
});
test('allowlist requires an exact file, term, and documented reason', () => {
    const source = entry('OpenAI');
    const allowed = [{ path: source.name, term: 'openai', reason: 'Test of a hypothetical required third-party notice.' }];
    assert.deepEqual(scanEntry(source, allowed), []);
    assert.ok(scanEntry(entry('OpenAI', 'product/another.php'), allowed).length);
    assert.throws(() => scanEntry(source, [{ path: source.name, term: 'openai' }]), /explanation/);
    assert.ok(scanEntry(entry("OpenAI\npassword = 'fixture-only-value'"), allowed).some(item => item.rule === 'credential-literal'));
});
test('reports file and line without echoing matching secrets', () => {
    const findings = scanEntry(entry("<?php\npassword = 'fixture-only-value'"));
    assert.equal(findings[0].line, 2);
    assert.ok(!JSON.stringify(findings).includes('fixture-only-value'));
});
test('detects UTF-16 workstation metadata', () => {
    assert.ok(scanEntry({ name: 'product/readme.txt', content: Buffer.concat([Buffer.from([255, 254]), Buffer.from('C:/Users/example', 'utf16le')]) }).length);
});
function chunk(type, data) {
    const result = Buffer.alloc(data.length + 12);
    result.writeUInt32BE(data.length);
    result.write(type, 4, 'ascii');
    data.copy(result, 8);
    return result;
}
function png(...chunks) {
    return Buffer.concat([Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]), ...chunks, chunk('IEND', Buffer.alloc(0))]);
}
test('scans PNG text metadata without treating compressed image pixels as text', () => {
    assert.equal(inspectableText(png(chunk('IDAT', Buffer.from('OpenAI C:/Users/not-metadata')))), '');
    for (const metadata of [
        chunk('tEXt', Buffer.from('Comment\0OpenAI')),
        chunk('zTXt', Buffer.concat([Buffer.from('Comment\0\0'), deflateSync(Buffer.from('OpenAI'))])),
        chunk('iTXt', Buffer.concat([Buffer.from('Comment\0\x01\0en\0Comment\0'), deflateSync(Buffer.from('OpenAI'))])),
    ]) assert.ok(scanEntry({ name: 'product/screenshot.png', content: png(metadata) }).some(item => item.rule === 'tooling-reference'));
});
test('fails closed on malformed image metadata', () => {
    assert.throws(() => inspectableText(png(chunk('tEXt', Buffer.from('text'))).subarray(0, 18)), /Truncated PNG/);
});
async function fixture(t) {
    const tempRoot = path.resolve(os.tmpdir());
    const prefix = path.join(tempRoot, 'manuscriptum-hygiene-');
    const directory = await mkdtemp(prefix);
    t.after(async () => {
        const resolved = path.resolve(directory);
        assert.equal(path.dirname(resolved), tempRoot);
        assert.ok(resolved.startsWith(prefix));
        await rm(resolved, { recursive: true, force: true });
    });
    const source = path.join(directory, 'source');
    await mkdir(source);
    const clean = entry('<?php\n// Runtime code.', 'product/runtime.php');
    await writeFile(path.join(source, 'runtime.php'), clean.content);
    const definition = { source, root: 'product', archive: path.join(directory, 'product.zip') };
    return { source, clean, definition, archive: entries => writeFile(definition.archive, createZip(entries)) };
}
test('accepts a real clean ZIP and verifies source bytes and file list', async t => {
    const f = await fixture(t);
    await f.archive([f.clean]);
    const report = await auditPackage(f.definition);
    assert.deepEqual(report.findings, []);
    assert.deepEqual(report.fileList, ['product/runtime.php']);
    assert.equal(report.files, 1);
    assert.match(report.sha256, /^[a-f0-9]{64}$/);
});
test('verifies builder exclusions against actual files in a source tree', async t => {
    const f = await fixture(t);
    for (const relative of ['AGENTS.md', '.env', 'tests/test.js', 'playwright/.auth/state.json', '.cache/report.txt', 'handoff_notes.md']) {
        const target = path.join(f.source, relative);
        await mkdir(path.dirname(target), { recursive: true });
        await writeFile(target, 'excluded');
    }
    const files = await collectFiles(f.source);
    assert.deepEqual(files.map(file => file.archivePath), ['runtime.php']);
    await f.archive([f.clean]);
    assert.deepEqual((await auditPackage(f.definition)).findings, []);
});
test('rejects contraband and secrets in a ZIP with clean source', async t => {
    const f = await fixture(t);
    await f.archive([f.clean, entry("password = 'fixture-only-value'", 'product/task-audit.md')]);
    const findings = (await auditPackage(f.definition)).findings;
    for (const rule of ['development-file', 'credential-literal', 'source-mismatch']) assert.ok(findings.some(item => item.rule === rule));
});
test('rejects stale, missing, and duplicate ZIP entries', async t => {
    const f = await fixture(t);
    await f.archive([entry('stale', f.clean.name), entry('stale', f.clean.name)]);
    const findings = (await auditPackage(f.definition)).findings;
    assert.ok(findings.some(item => item.rule === 'source-mismatch'));
    assert.ok(findings.some(item => item.rule === 'duplicate-entry'));
    await f.archive([]);
    assert.ok((await auditPackage(f.definition)).findings.some(item => item.rule === 'missing-source-file'));
});
test('checks source content even if the existing ZIP was clean', async t => {
    const f = await fixture(t);
    await f.archive([f.clean]);
    await writeFile(path.join(f.source, 'runtime.php'), 'OpenAI');
    assert.ok((await auditPackage(f.definition)).findings.some(item => item.surface === 'source' && item.rule === 'tooling-reference'));
});
test('rejects malformed ZIPs and traversal paths', async t => {
    const f = await fixture(t);
    await writeFile(f.definition.archive, 'invalid archive');
    await assert.rejects(auditPackage(f.definition), /ZIP/);
    await f.archive([entry('runtime', '../escape.php')]);
    await assert.rejects(auditPackage(f.definition), /unsafe path/);
});
